# ruff
[tool.ruff]
ignore-init-module-imports = true

[tool.ruff.format]
skip-magic-trailing-comma = false
docstring-code-format = true


# isort
[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true


# bandit
[tool.bandit]
skips = ["B101"]
