from typing import Optional
from pydantic import BaseModel
from wechatter.models.github.base import User, Repository


class PrRepository(Repository):
    allow_squash_merge: bool
    allow_merge_commit: bool
    allow_rebase_merge: bool
    allow_auto_merge: bool
    delete_branch_on_merge: bool
    allow_update_branch: bool
    use_squash_pr_title_as_default: bool
    squash_merge_commit_message: str
    squash_merge_commit_title: str
    merge_commit_message: str
    merge_commit_title: str


class PrBranch(BaseModel):
    label: str
    ref: str
    sha: str
    user: User
    repo: PrRepository


class PullRequest(BaseModel):
    html_url: str
    issue_url: str
    number: int
    state: str
    title: str
    user: User
    body: Optional[str]
    base: PrBranch
    head: PrBranch


class GithubPrWebhook(BaseModel):
    action: str
    number: int
    pull_request: PullRequest
    repository: Repository
    sender: User


"""
{
  "action": "opened",
  "number": 2,
  "pull_request": {
    "url": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls/2",
    "id": 1691266396,
    "node_id": "PR_kwDOLBhCe85kzq1c",
    "html_url": "https://github.com/Cassius0924/.dotfiles/pull/2",
    "issue_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/2",
    "number": 2,
    "state": "open",
    "locked": false,
    "title": "Update config.yml",
    "user": {
      "login": "Cassius0924",
      "id": 62874592,
      "node_id": "MDQ6VXNlcjYyODc0NTky",
      "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Cassius0924",
      "html_url": "https://github.com/Cassius0924",
      "followers_url": "https://api.github.com/users/Cassius0924/followers",
      "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
      "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
      "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
      "repos_url": "https://api.github.com/users/Cassius0924/repos",
      "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": null,
    "created_at": "2024-01-23T08:32:29Z",
    "updated_at": "2024-01-23T08:32:29Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [

    ],
    "milestone": null,
    "draft": false,
    "commits_url": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls/2/commits",
    "review_comments_url": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls/2/comments",
    "review_comment_url": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/2/comments",
    "statuses_url": "https://api.github.com/repos/Cassius0924/.dotfiles/statuses/c793f3eb72f0612ee9adf8ee52d6aaf995a455fe",
    "head": {
      "label": "Cassius0924:test_webhook",
      "ref": "test_webhook",
      "sha": "c793f3eb72f0612ee9adf8ee52d6aaf995a455fe",
      "user": {
        "login": "Cassius0924",
        "id": 62874592,
        "node_id": "MDQ6VXNlcjYyODc0NTky",
        "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Cassius0924",
        "html_url": "https://github.com/Cassius0924",
        "followers_url": "https://api.github.com/users/Cassius0924/followers",
        "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
        "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
        "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
        "repos_url": "https://api.github.com/users/Cassius0924/repos",
        "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 739787387,
        "node_id": "R_kgDOLBhCew",
        "name": ".dotfiles",
        "full_name": "Cassius0924/.dotfiles",
        "private": true,
        "owner": {
          "login": "Cassius0924",
          "id": 62874592,
          "node_id": "MDQ6VXNlcjYyODc0NTky",
          "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Cassius0924",
          "html_url": "https://github.com/Cassius0924",
          "followers_url": "https://api.github.com/users/Cassius0924/followers",
          "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
          "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
          "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
          "repos_url": "https://api.github.com/users/Cassius0924/repos",
          "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/Cassius0924/.dotfiles",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/Cassius0924/.dotfiles",
        "forks_url": "https://api.github.com/repos/Cassius0924/.dotfiles/forks",
        "keys_url": "https://api.github.com/repos/Cassius0924/.dotfiles/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Cassius0924/.dotfiles/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Cassius0924/.dotfiles/teams",
        "hooks_url": "https://api.github.com/repos/Cassius0924/.dotfiles/hooks",
        "issue_events_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Cassius0924/.dotfiles/events",
        "assignees_url": "https://api.github.com/repos/Cassius0924/.dotfiles/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Cassius0924/.dotfiles/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Cassius0924/.dotfiles/tags",
        "blobs_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Cassius0924/.dotfiles/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Cassius0924/.dotfiles/languages",
        "stargazers_url": "https://api.github.com/repos/Cassius0924/.dotfiles/stargazers",
        "contributors_url": "https://api.github.com/repos/Cassius0924/.dotfiles/contributors",
        "subscribers_url": "https://api.github.com/repos/Cassius0924/.dotfiles/subscribers",
        "subscription_url": "https://api.github.com/repos/Cassius0924/.dotfiles/subscription",
        "commits_url": "https://api.github.com/repos/Cassius0924/.dotfiles/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Cassius0924/.dotfiles/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Cassius0924/.dotfiles/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Cassius0924/.dotfiles/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Cassius0924/.dotfiles/merges",
        "archive_url": "https://api.github.com/repos/Cassius0924/.dotfiles/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Cassius0924/.dotfiles/downloads",
        "issues_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Cassius0924/.dotfiles/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Cassius0924/.dotfiles/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Cassius0924/.dotfiles/labels{/name}",
        "releases_url": "https://api.github.com/repos/Cassius0924/.dotfiles/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Cassius0924/.dotfiles/deployments",
        "created_at": "2024-01-06T14:45:21Z",
        "updated_at": "2024-01-06T14:50:57Z",
        "pushed_at": "2024-01-23T08:32:30Z",
        "git_url": "git://github.com/Cassius0924/.dotfiles.git",
        "ssh_url": "git@github.com:Cassius0924/.dotfiles.git",
        "clone_url": "https://github.com/Cassius0924/.dotfiles.git",
        "svn_url": "https://github.com/Cassius0924/.dotfiles",
        "homepage": null,
        "size": 4,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Lua",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "private",
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "base": {
      "label": "Cassius0924:master",
      "ref": "master",
      "sha": "a4fb7a6812424ac7d19a6c7f548d492c0bea6e85",
      "user": {
        "login": "Cassius0924",
        "id": 62874592,
        "node_id": "MDQ6VXNlcjYyODc0NTky",
        "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Cassius0924",
        "html_url": "https://github.com/Cassius0924",
        "followers_url": "https://api.github.com/users/Cassius0924/followers",
        "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
        "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
        "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
        "repos_url": "https://api.github.com/users/Cassius0924/repos",
        "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 739787387,
        "node_id": "R_kgDOLBhCew",
        "name": ".dotfiles",
        "full_name": "Cassius0924/.dotfiles",
        "private": true,
        "owner": {
          "login": "Cassius0924",
          "id": 62874592,
          "node_id": "MDQ6VXNlcjYyODc0NTky",
          "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Cassius0924",
          "html_url": "https://github.com/Cassius0924",
          "followers_url": "https://api.github.com/users/Cassius0924/followers",
          "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
          "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
          "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
          "repos_url": "https://api.github.com/users/Cassius0924/repos",
          "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/Cassius0924/.dotfiles",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/Cassius0924/.dotfiles",
        "forks_url": "https://api.github.com/repos/Cassius0924/.dotfiles/forks",
        "keys_url": "https://api.github.com/repos/Cassius0924/.dotfiles/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Cassius0924/.dotfiles/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Cassius0924/.dotfiles/teams",
        "hooks_url": "https://api.github.com/repos/Cassius0924/.dotfiles/hooks",
        "issue_events_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Cassius0924/.dotfiles/events",
        "assignees_url": "https://api.github.com/repos/Cassius0924/.dotfiles/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Cassius0924/.dotfiles/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Cassius0924/.dotfiles/tags",
        "blobs_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Cassius0924/.dotfiles/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Cassius0924/.dotfiles/languages",
        "stargazers_url": "https://api.github.com/repos/Cassius0924/.dotfiles/stargazers",
        "contributors_url": "https://api.github.com/repos/Cassius0924/.dotfiles/contributors",
        "subscribers_url": "https://api.github.com/repos/Cassius0924/.dotfiles/subscribers",
        "subscription_url": "https://api.github.com/repos/Cassius0924/.dotfiles/subscription",
        "commits_url": "https://api.github.com/repos/Cassius0924/.dotfiles/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Cassius0924/.dotfiles/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Cassius0924/.dotfiles/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Cassius0924/.dotfiles/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Cassius0924/.dotfiles/merges",
        "archive_url": "https://api.github.com/repos/Cassius0924/.dotfiles/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Cassius0924/.dotfiles/downloads",
        "issues_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Cassius0924/.dotfiles/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Cassius0924/.dotfiles/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Cassius0924/.dotfiles/labels{/name}",
        "releases_url": "https://api.github.com/repos/Cassius0924/.dotfiles/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Cassius0924/.dotfiles/deployments",
        "created_at": "2024-01-06T14:45:21Z",
        "updated_at": "2024-01-06T14:50:57Z",
        "pushed_at": "2024-01-23T08:32:30Z",
        "git_url": "git://github.com/Cassius0924/.dotfiles.git",
        "ssh_url": "git@github.com:Cassius0924/.dotfiles.git",
        "clone_url": "https://github.com/Cassius0924/.dotfiles.git",
        "svn_url": "https://github.com/Cassius0924/.dotfiles",
        "homepage": null,
        "size": 4,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Lua",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "private",
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls/2"
      },
      "html": {
        "href": "https://github.com/Cassius0924/.dotfiles/pull/2"
      },
      "issue": {
        "href": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/2"
      },
      "comments": {
        "href": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/2/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls/2/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls/2/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/Cassius0924/.dotfiles/statuses/c793f3eb72f0612ee9adf8ee52d6aaf995a455fe"
      }
    },
    "author_association": "OWNER",
    "auto_merge": null,
    "active_lock_reason": null,
    "merged": false,
    "mergeable": null,
    "rebaseable": null,
    "mergeable_state": "unknown",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 0,
    "deletions": 0,
    "changed_files": 0
  },
  "repository": {
    "id": 739787387,
    "node_id": "R_kgDOLBhCew",
    "name": ".dotfiles",
    "full_name": "Cassius0924/.dotfiles",
    "private": true,
    "owner": {
      "login": "Cassius0924",
      "id": 62874592,
      "node_id": "MDQ6VXNlcjYyODc0NTky",
      "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Cassius0924",
      "html_url": "https://github.com/Cassius0924",
      "followers_url": "https://api.github.com/users/Cassius0924/followers",
      "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
      "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
      "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
      "repos_url": "https://api.github.com/users/Cassius0924/repos",
      "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Cassius0924/.dotfiles",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Cassius0924/.dotfiles",
    "forks_url": "https://api.github.com/repos/Cassius0924/.dotfiles/forks",
    "keys_url": "https://api.github.com/repos/Cassius0924/.dotfiles/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Cassius0924/.dotfiles/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Cassius0924/.dotfiles/teams",
    "hooks_url": "https://api.github.com/repos/Cassius0924/.dotfiles/hooks",
    "issue_events_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Cassius0924/.dotfiles/events",
    "assignees_url": "https://api.github.com/repos/Cassius0924/.dotfiles/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Cassius0924/.dotfiles/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Cassius0924/.dotfiles/tags",
    "blobs_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Cassius0924/.dotfiles/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Cassius0924/.dotfiles/languages",
    "stargazers_url": "https://api.github.com/repos/Cassius0924/.dotfiles/stargazers",
    "contributors_url": "https://api.github.com/repos/Cassius0924/.dotfiles/contributors",
    "subscribers_url": "https://api.github.com/repos/Cassius0924/.dotfiles/subscribers",
    "subscription_url": "https://api.github.com/repos/Cassius0924/.dotfiles/subscription",
    "commits_url": "https://api.github.com/repos/Cassius0924/.dotfiles/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Cassius0924/.dotfiles/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Cassius0924/.dotfiles/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Cassius0924/.dotfiles/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Cassius0924/.dotfiles/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Cassius0924/.dotfiles/merges",
    "archive_url": "https://api.github.com/repos/Cassius0924/.dotfiles/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Cassius0924/.dotfiles/downloads",
    "issues_url": "https://api.github.com/repos/Cassius0924/.dotfiles/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Cassius0924/.dotfiles/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Cassius0924/.dotfiles/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Cassius0924/.dotfiles/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Cassius0924/.dotfiles/labels{/name}",
    "releases_url": "https://api.github.com/repos/Cassius0924/.dotfiles/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Cassius0924/.dotfiles/deployments",
    "created_at": "2024-01-06T14:45:21Z",
    "updated_at": "2024-01-06T14:50:57Z",
    "pushed_at": "2024-01-23T08:32:30Z",
    "git_url": "git://github.com/Cassius0924/.dotfiles.git",
    "ssh_url": "git@github.com:Cassius0924/.dotfiles.git",
    "clone_url": "https://github.com/Cassius0924/.dotfiles.git",
    "svn_url": "https://github.com/Cassius0924/.dotfiles",
    "homepage": null,
    "size": 4,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Lua",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "private",
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "Cassius0924",
    "id": 62874592,
    "node_id": "MDQ6VXNlcjYyODc0NTky",
    "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Cassius0924",
    "html_url": "https://github.com/Cassius0924",
    "followers_url": "https://api.github.com/users/Cassius0924/followers",
    "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
    "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
    "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
    "repos_url": "https://api.github.com/users/Cassius0924/repos",
    "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
    "type": "User",
    "site_admin": false
  }
}
"""
