name: Build and Push Docker Image On Release

on:
  release:
    types:
      - published

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.1.0
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: cassius0924
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.2.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: cassius0924/wechatter:${{ github.event.release.tag_name }}
